---

kind: pipeline
type: docker
name: php-8.0

# disable drone built-in clone action (always runs as root)
clone:
  disable: true
steps:
  - name: test-php-8.0
    image: shaarli/drone-ci-base:8.0
    # pull: always # force update of base image even if cached locally
    commands:
      # git clone as drone user
      - git clone --depth=50 --branch=$DRONE_BRANCH $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT
      - composer config --unset platform && composer config platform.php 8.0
      - composer self-update --2
      - composer update --ignore-platform-req=php
      - composer remove --dev --ignore-platform-req=php phpunit/phpunit
      - composer require --dev --ignore-platform-req=php phpunit/php-text-template ^2.0
      - composer require --dev --ignore-platform-req=php phpunit/phpunit ^9.0
      - make clean
      - make check_permissions
      - make code_sniffer
      - make all_tests

---

kind: pipeline
type: docker
name: php-7.4

clone:
  disable: true
steps:
  - name: test-php-7.4
    image: shaarli/drone-ci-base:7.4
    # pull: always # force update of base image even if cached locally
    commands:
      - git clone --depth=50 --branch=$DRONE_BRANCH $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT
      - composer config --unset platform && composer config platform.php 7.4
      - composer update
      - make clean
      - make check_permissions
      - make code_sniffer
      - make all_tests

---

kind: pipeline
type: docker
name: php-7.3

clone:
  disable: true
steps:
  - name: test-php-7.3
    image: shaarli/drone-ci-base:7.3
    # pull: always # force update of base image even if cached locally
    commands:
      - git clone --depth=50 --branch=$DRONE_BRANCH $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT
      - composer config --unset platform && composer config platform.php 7.3
      - composer update
      - make clean
      - make check_permissions
      - make code_sniffer
      - make all_tests

---

kind: pipeline
type: docker
name: php-7.2

clone:
  disable: true
steps:
  - name: test-php-7.2
    image: shaarli/drone-ci-base:7.2
    # pull: always # force update of base image even if cached locally
    commands:
      - git clone --depth=50 --branch=$DRONE_BRANCH $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT
      - composer config --unset platform && composer config platform.php 7.2
      - composer update
      - make clean
      - make check_permissions
      - make code_sniffer
      - make all_tests

---

kind: pipeline
type: docker
name: php-7.1

clone:
  disable: true
steps:
  - name: test-php-7.1
    image: shaarli/drone-ci-base:7.1
    # pull: always # force update of base image even if cached locally
    commands:
      - git clone --depth=50 --branch=$DRONE_BRANCH $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT
      - composer config --unset platform && composer config platform.php 7.1
      - composer update
      - make clean
      - make check_permissions
      - make code_sniffer
      - make all_tests

---

kind: pipeline
type: docker
name: node-10

clone:
  disable: true
steps:
  - name: test-node-10
    image: node:10
    commands:
      - git clone --depth=50 --branch=$DRONE_BRANCH $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT
      - yarn install
      - yarn run build # verify successful frontend builds
      - make eslint # javascript static analysis
      - make sasslint # linter for SASS syntax

---

kind: pipeline
type: docker
name: python-3.6

steps:
  - name: test-python-3.6
    image: python:3.6-slim
    commands:
      - pip install mkdocs
      - mkdocs build --clean
