---
kind: pipeline
type: docker
name: php-7.4

clone:
  disable: true

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - /drone/.composer/cache

- name: test-php-7.4
  image: shaarli/drone-ci-base:7.4-add-zip
  commands:
    - git clone --depth=50 --branch=$DRONE_BRANCH https://github.com/nodiscc/Shaarli.git .
    - git checkout $DRONE_COMMIT
    - composer config --unset platform && composer config platform.php 7.4
    - composer update
    # - PATH=${PATH//:\.\/node_modules\/\.bin/}
    - make clean
    - make check_permissions
    - make code_sniffer
    - make all_tests

---
kind: pipeline
type: docker
name: php-7.3

clone:
  disable: true

steps:
- name: test-php-7.3
  image: shaarli/drone-ci-base:7.3-add-zip
  commands:
    - git clone --depth=50 --branch=$DRONE_BRANCH https://github.com/nodiscc/Shaarli.git .
    - git checkout $DRONE_COMMIT
    - composer config --unset platform && composer config platform.php 7.3
    - composer update
    # - PATH=${PATH//:\.\/node_modules\/\.bin/}
    - make clean
    - make check_permissions
    - make code_sniffer
    - make all_tests
