kind: pipeline
type: docker
name: default

steps:
- name: build
  image: php:${PHP_VERSION}
  commands:
    - apt update && apt install make git
    - composer update
    - make clean
    - make check_permissions
    - make code_sniffer
    - make all_tests

matrix:
  PHP_VERSION:
   - 7.4
   - 7.3
   - 7.2
   - 7.1

