kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine:3.12
  commands:
    - apk update && apk add make git php7
    - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
    - make clean
    - make check_permissions
    - make code_sniffer
    - make all_tests

