name: Build/push Docker image (master/latest)
on:
  push:
    branches: [ master, docker-latest-replace-dev-with-hash ]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set shaarli version to the latest commit hash
        run: sed -i "s/dev/$(git rev-parse --short HEAD)/" shaarli_version.php
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nodiscc/shaarli:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
